apiVersion: v1
kind: Pod
metadata:
  name: bd-mysql
  labels:
    app: bd-mysql
spec:
  containers:
    - name: bd-mysql
      image: mysql:5.6
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
      ports:
        - containerPort: 3306